services:

  mongo:
    image: mongo:8.0-rc
    container_name: mongo
    restart: unless-stopped
    env_file: dotenv/mongo.env
    networks:
      - geuebt_backend
    ports:
      - '0.0.0.0:27017:27017'
    volumes:
      - mongo_db:/data/db:rw
      - logfiles:/var/log/mongodb:rw
      - ./config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./config/mongod.conf:/etc/mongod.conf:ro
    command: --config /etc/mongod.conf

  # fastapi:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: fastapi
  #   restart: unless-stopped
  #   env_file: dotenv/fastapi.env
  #   networks:
  #     - geuebt_backend
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - mongo

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    env_file: dotenv/mongo.env
    networks:
      - geuebt_backend
    ports:
      - '0.0.0.0:8081:8081'
    depends_on:
      - mongo

## Docker Resources ####################################

volumes:
  mongo_db:
    external: true
  logfiles:
    external: true

networks:
  geuebt_backend:
    name: geuebt_backend